<a href="https://colab.research.google.com/github/Siddharth5723/Daily_learning/blob/main/Naive_bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

# Creating the dataset as a list of dictionaries
titanic_data = [
    {"PassengerId": 1, "Name": "Braund, Mr. Owen Harris", "Pclass": 3, "Sex": "male", "Age": 22.0, "SibSp": 1, "Parch": 0, "Ticket": "A/5 21171", "Fare": 7.25, "Cabin": None, "Embarked": "S", "Survived": 0},
    {"PassengerId": 2, "Name": "Cumings, Mrs. John Bradley (Florence Briggs Thayer)", "Pclass": 1, "Sex": "female", "Age": 38.0, "SibSp": 1, "Parch": 0, "Ticket": "PC 17599", "Fare": 71.2833, "Cabin": "C85", "Embarked": "C", "Survived": 1},
    {"PassengerId": 3, "Name": "Heikkinen, Miss. Laina", "Pclass": 3, "Sex": "female", "Age": 26.0, "SibSp": 0, "Parch": 0, "Ticket": "STON/O2. 3101282", "Fare": 7.925, "Cabin": None, "Embarked": "S", "Survived": 1},
    {"PassengerId": 4, "Name": "Futrelle, Mrs. Jacques Heath (Lily May Peel)", "Pclass": 1, "Sex": "female", "Age": 35.0, "SibSp": 1, "Parch": 0, "Ticket": "113803", "Fare": 53.1, "Cabin": "C123", "Embarked": "S", "Survived": 1},
    {"PassengerId": 5, "Name": "Allen, Mr. William Henry", "Pclass": 3, "Sex": "male", "Age": 35.0, "SibSp": 0, "Parch": 0, "Ticket": "373450", "Fare": 8.05, "Cabin": None, "Embarked": "S", "Survived": 0},
    {"PassengerId": 6, "Name": "Moran, Mr. James", "Pclass": 3, "Sex": "male", "Age": np.nan, "SibSp": 0, "Parch": 0, "Ticket": "330877", "Fare": 8.4583, "Cabin": None, "Embarked": "Q", "Survived": 0},
    {"PassengerId": 7, "Name": "McCarthy, Mr. Timothy J", "Pclass": 1, "Sex": "male", "Age": 54.0, "SibSp": 0, "Parch": 0, "Ticket": "17463", "Fare": 51.8625, "Cabin": "E46", "Embarked": "S", "Survived": 0},
    {"PassengerId": 8, "Name": "Palsson, Master. Gosta Leonard", "Pclass": 3, "Sex": "male", "Age": 2.0, "SibSp": 3, "Parch": 1, "Ticket": "349909", "Fare": 21.075, "Cabin": None, "Embarked": "S", "Survived": 0},
    {"PassengerId": 9, "Name": "Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)", "Pclass": 3, "Sex": "female", "Age": 27.0, "SibSp": 0, "Parch": 2, "Ticket": "347742", "Fare": 11.1333, "Cabin": None, "Embarked": "S", "Survived": 1},
    {"PassengerId": 10, "Name": "Nasser, Mrs. Nicholas (Adele Achem)", "Pclass": 2, "Sex": "female", "Age": 14.0, "SibSp": 1, "Parch": 0, "Ticket": "237736", "Fare": 30.0708, "Cabin": None, "Embarked": "C", "Survived": 1},
    {"PassengerId": 11, "Name": "Sandstrom, Miss. Marguerite Rut", "Pclass": 3, "Sex": "female", "Age": 4.0, "SibSp": 1, "Parch": 1, "Ticket": "PP 9549", "Fare": 16.7, "Cabin": "G6", "Embarked": "S", "Survived": 1},
    {"PassengerId": 12, "Name": "Bonnell, Miss. Elizabeth", "Pclass": 1, "Sex": "female", "Age": 58.0, "SibSp": 0, "Parch": 0, "Ticket": "113783", "Fare": 26.55, "Cabin": "C103", "Embarked": "S", "Survived": 1},
    {"PassengerId": 13, "Name": "Saundercock, Mr. William Henry", "Pclass": 3, "Sex": "male", "Age": 20.0, "SibSp": 0, "Parch": 0, "Ticket": "A/5. 2151", "Fare": 8.05, "Cabin": None, "Embarked": "S", "Survived": 0},
    {"PassengerId": 14, "Name": "Andersson, Mr. Anders Johan", "Pclass": 3, "Sex": "male", "Age": 39.0, "SibSp": 1, "Parch": 5, "Ticket": "347082", "Fare": 31.275, "Cabin": None, "Embarked": "S", "Survived": 0},
    {"PassengerId": 15, "Name": "Vestrom, Miss. Hulda Amanda Adolfina", "Pclass": 3, "Sex": "female", "Age": 14.0, "SibSp": 0, "Parch": 0, "Ticket": "350406", "Fare": 7.8542, "Cabin": None, "Embarked": "S", "Survived": 0},
    {"PassengerId": 16, "Name": "Hewlett, Mrs. (Mary D Kingcome)", "Pclass": 2, "Sex": "female", "Age": 55.0, "SibSp": 0, "Parch": 0, "Ticket": "248706", "Fare": 16.0, "Cabin": None, "Embarked": "S", "Survived": 1},
    {"PassengerId": 17, "Name": "Rice, Master. Eugene", "Pclass": 3, "Sex": "male", "Age": 2.0, "SibSp": 4, "Parch": 1, "Ticket": "382652", "Fare": 29.125, "Cabin": None, "Embarked": "Q", "Survived": 0},
    {"PassengerId": 18, "Name": "Williams, Mr. Charles Eugene", "Pclass": 2, "Sex": "male", "Age": np.nan, "SibSp": 0, "Parch": 0, "Ticket": "244373", "Fare": 13.0, "Cabin": None, "Embarked": "S", "Survived": 1},
    {"PassengerId": 19, "Name": "Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)", "Pclass": 3, "Sex": "female", "Age": 31.0, "SibSp": 1, "Parch": 0, "Ticket": "345763", "Fare": 18.0, "Cabin": None, "Embarked": "S", "Survived": 0},
    {"PassengerId": 20, "Name": "Masselmani, Mrs. Fatima", "Pclass": 3, "Sex": "female", "Age": np.nan, "SibSp": 0, "Parch": 0, "Ticket": "2649", "Fare": 7.225, "Cabin": None, "Embarked": "C", "Survived": 1},
    {"PassengerId": 21, "Name": "Fynney, Mr. Joseph J", "Pclass": 2, "Sex": "male", "Age": 35.0, "SibSp": 0, "Parch": 0, "Ticket": "239865", "Fare": 26.0, "Cabin": None, "Embarked": "S", "Survived": 0},
    {"PassengerId": 22, "Name": "Beesley, Mr. Lawrence", "Pclass": 2, "Sex": "male", "Age": 34.0, "SibSp": 0, "Parch": 0, "Ticket": "248698", "Fare": 13.0, "Cabin": "D56", "Embarked": "S", "Survived": 1},
    {"PassengerId": 23, "Name": "McGowan, Miss. Anna \"Annie\"", "Pclass": 3, "Sex": "female", "Age": 15.0, "SibSp": 0, "Parch": 0, "Ticket": "330923", "Fare": 8.0292, "Cabin": None, "Embarked": "Q", "Survived": 1},
    {"PassengerId": 24, "Name": "Sloper, Mr. William Thompson", "Pclass": 1, "Sex": "male", "Age": 28.0, "SibSp": 0, "Parch": 0, "Ticket": "113788", "Fare": 35.5, "Cabin": "A6", "Embarked": "S", "Survived": 1},
    {"PassengerId": 25, "Name": "Palsson, Miss. Torborg Danira", "Pclass": 3, "Sex": "female", "Age": 8.0, "SibSp": 3, "Parch": 1, "Ticket": "349909", "Fare": 21.075, "Cabin": None, "Embarked": "S", "Survived": 0},
    {"PassengerId": 26, "Name": "Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)", "Pclass": 3, "Sex": "female", "Age": 38.0, "SibSp": 1, "Parch": 5, "Ticket": "347077", "Fare": 31.3875, "Cabin": None, "Embarked": "S", "Survived": 1},
    {"PassengerId": 27, "Name": "Emir, Mr. Farred Chehab", "Pclass": 3, "Sex": "male", "Age": np.nan, "SibSp": 0, "Parch": 0, "Ticket": "2631", "Fare": 7.225, "Cabin": None, "Embarked": "C", "Survived": 0},
    {"PassengerId": 28, "Name": "Fortune, Mr. Charles Alexander", "Pclass": 1, "Sex": "male", "Age": 19.0, "SibSp": 3, "Parch": 2, "Ticket": "19950", "Fare": 263.0, "Cabin": "C23 C25 C27", "Embarked": "S", "Survived": 0},
    {"PassengerId": 29, "Name": "O'Dwyer, Miss. Ellen \"Nellie\"", "Pclass": 3, "Sex": "female", "Age": np.nan, "SibSp": 0, "Parch": 0, "Ticket": "330959", "Fare": 7.8792, "Cabin": None, "Embarked": "Q", "Survived": 1},
    {"PassengerId": 30, "Name": "Todoroff, Mr. Lalio", "Pclass": 3, "Sex": "male", "Age": np.nan, "SibSp": 0, "Parch": 0, "Ticket": "349216", "Fare": 7.8958, "Cabin": None, "Embarked": "S", "Survived": 0},
    {"PassengerId": 31, "Name": "Uruchurtu, Don. Manuel E", "Pclass": 1, "Sex": "male", "Age": 40.0, "SibSp": 0, "Parch": 0, "Ticket": "PC 17601", "Fare": 27.7208, "Cabin": None, "Embarked": "C", "Survived": 0},
    {"PassengerId": 32, "Name": "Spencer, Mrs. William Augustus (Marie Eugenie)", "Pclass": 1, "Sex": "female", "Age": np.nan, "SibSp": 1, "Parch": 0, "Ticket": "PC 17569", "Fare": 146.5208, "Cabin": "B78", "Embarked": "C", "Survived": 1},
    {"PassengerId": 33, "Name": "Glynn, Miss. Mary Agatha", "Pclass": 3, "Sex": "female", "Age": np.nan, "SibSp": 0, "Parch": 0, "Ticket": "335677", "Fare": 7.75, "Cabin": None, "Embarked": "Q", "Survived": 1},
    {"PassengerId": 34, "Name": "Wheadon, Mr. Edward H", "Pclass": 2, "Sex": "male", "Age": 66.0, "SibSp": 0, "Parch": 0, "Ticket": "C.A. 24579", "Fare": 10.5, "Cabin": None, "Embarked": "S", "Survived": 0},
    {"PassengerId": 35, "Name": "Meyer, Mr. Edgar Joseph", "Pclass": 1, "Sex": "male", "Age": 28.0, "SibSp": 1, "Parch": 0, "Ticket": "PC 17604", "Fare": 82.1708, "Cabin": None, "Embarked": "C", "Survived": 0},
    {"PassengerId": 36, "Name": "Holverson, Mr. Alexander Oskar", "Pclass": 1, "Sex": "male", "Age": 42.0, "SibSp": 1, "Parch": 0, "Ticket": "113789", "Fare": 52.0, "Cabin": None, "Embarked": "S", "Survived": 0},
    {"PassengerId": 37, "Name": "Mamee, Mr. Hanna", "Pclass": 3, "Sex": "male", "Age": np.nan, "SibSp": 0, "Parch": 0, "Ticket": "2677", "Fare": 7.2292, "Cabin": None, "Embarked": "C", "Survived": 1},
    {"PassengerId": 38, "Name": "Cann, Mr. Ernest Charles", "Pclass": 3, "Sex": "male", "Age": 21.0, "SibSp": 0, "Parch": 0, "Ticket": "A./5. 2152", "Fare": 8.05, "Cabin": None, "Embarked": "S", "Survived": 0},
    {"PassengerId": 39, "Name": "Vander Planke, Miss. Augusta Maria", "Pclass": 3, "Sex": "female", "Age": 18.0, "SibSp": 2, "Parch": 0, "Ticket": "345764", "Fare": 18.0, "Cabin": None, "Embarked": "S", "Survived": 0},
    {"PassengerId": 40, "Name": "Nicola-Yarred, Miss. Jamila", "Pclass": 3, "Sex": "female", "Age": 14.0, "SibSp": 1, "Parch": 0, "Ticket": "2651", "Fare": 11.2417, "Cabin": None, "Embarked": "C", "Survived": 1}
]

# Initializing the DataFrame
df = pd.DataFrame(titanic_data)

In [2]:
df.head()

,PassengerId,Name,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",3,male,22.0,1,0,A/5 21171,7.2500,None,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",3,female,26.0,0,0,STON/O2. 3101282,7.9250,None,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,female,35.0,1,0,113803,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",3,male,35.0,0,0,373450,8.0500,None,S,0

In [3]:
df.isnull().sum()

PassengerId     0
Name            0
Pclass          0
Sex             0
Age             9
SibSp           0
Parch           0
Ticket          0
Fare            0
Cabin          31
Embarked        0
Survived        0
dtype: int64

In [6]:
df = df.drop(columns=['Cabin'])

In [8]:
df.isnull().sum()

PassengerId    0
Name           0
Pclass         0
Sex            0
Age            9
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
Survived       0
dtype: int64

In [10]:
df.drop(['PassengerId','Name' , 'SibSp' , 'Parch', 'Ticket' , 'Embarked'],axis='columns',inplace=True)
df.head()

   Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [11]:
target = df.Survived
inputs = df.drop('Survived', axis='columns')

In [26]:
dummies = pd.get_dummies(inputs.Sex, dtype=int)
dummies.head(3)

   female  male
0       0     1
1       1     0
2       1     0

In [38]:
inputs = pd.concat([inputs,dummies], axis='columns')
inputs.head(3)

   Pclass     Sex   Age     Fare  female  male
0       3    male  22.0   7.2500       0     1
1       1  female  38.0  71.2833       1     0
2       3  female  26.0   7.9250       1     0

In [39]:
inputs.columns[inputs.isna().any()]

Index([], dtype='object')

In [40]:
inputs.Age[::10]

0     22.0
10     4.0
20    35.0
30    40.0
Name: Age, dtype: float64

In [42]:
inputs = inputs.drop(columns = ['Sex'])

In [43]:
inputs.head()

   Pclass   Age     Fare  female  male
0       3  22.0   7.2500       0     1
1       1  38.0  71.2833       1     0
2       3  26.0   7.9250       1     0
3       1  35.0  53.1000       1     0
4       3  35.0   8.0500       0     1

In [56]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train , y_test = train_test_split(inputs, target, test_size=0.2)

In [57]:
len(X_train)

32

In [58]:
len(X_test)

8

In [59]:
X_train

    Pclass        Age      Fare  female  male
24       3   8.000000   21.0750       1     0
20       2  35.000000   26.0000       0     1
31       1  28.451613  146.5208       1     0
35       1  42.000000   52.0000       0     1
37       3  21.000000    8.0500       0     1
14       3  14.000000    7.8542       1     0
36       3  28.451613    7.2292       0     1
33       2  66.000000   10.5000       0     1
26       3  28.451613    7.2250       0     1
3        1  35.000000   53.1000       1     0
0        3  22.000000    7.2500       0     1
13       3  39.000000   31.2750       0     1
4        3  35.000000    8.0500       0     1
15       2  55.000000   16.0000       1     0
27       1  19.000000  263.0000       0     1
5        3  28.451613    8.4583       0     1
19       3  28.451613    7.2250       1     0
1        1  38.000000   71.2833       1     0
17       2  28.451613   13.0000       0     1
21       2  34.000000   13.0000       0     1
8        3  27.000000   11.1333       1     0
30       1  40.000000   27.7208       0     1
6        1  54.000000   51.8625       0     1
16       3   2.000000   29.1250       0     1
32       3  28.451613    7.7500       1     0
9        2  14.000000   30.0708       1     0
39       3  14.000000   11.2417       1     0
12       3  20.000000    8.0500       0     1
25       3  38.000000   31.3875       1     0
38       3  18.000000   18.0000       1     0
11       1  58.000000   26.5500       1     0
29       3  28.451613    7.8958       0     1

In [60]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [61]:
model.fit(X_train , y_train)

GaussianNB()

In [62]:
model.score(X_test , y_test)

0.75

In [65]:
y_test[:10]

18    0
2     1
7     0
34    0
10    1
28    1
22    1
23    1
Name: Survived, dtype: int64

In [64]:
model.predict(X_test[:10])

array([1, 1, 0, 0, 1, 1, 1, 0])

In [67]:
model.predict_proba(X_test[:10])

array([[0.0095778 , 0.9904222 ],
       [0.01180323, 0.98819677],
       [0.99471415, 0.00528585],
       [0.9641806 , 0.0358194 ],
       [0.04217043, 0.95782957],
       [0.01099275, 0.98900725],
       [0.0197721 , 0.9802279 ],
       [0.93808546, 0.06191454]])